# Generated by Django 6.0.1 on 2026-02-11 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official/branding name of the provider', max_length=120, verbose_name='Service Provider Name')),
                ('is_approved', models.BooleanField(default=False, help_text='Service Provider approve', verbose_name='Serive Provider approve')),
                ('business_registration_number', models.CharField(help_text='Commercial registration number (CR)', max_length=50, unique=True, verbose_name='Business Registration Number')),
                ('contact_person_name', models.CharField(max_length=100, verbose_name='Contact Person Name')),
                ('phone_number', models.CharField(help_text='Preferred format: +9665xxxxxxxx or 9665xxxxxxxx', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('settlement_cycle_days', models.PositiveIntegerField(default=7, help_text='Number of days after delivery until payment (e.g. 7, 15, 30)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Settlement Cycle')),
                ('markup_type', models.CharField(choices=[('fixed', 'Fixed Amount (SAR)'), ('percentage', 'Percentage (%)')], default='percentage', max_length=20, verbose_name='Markup Type')),
                ('markup_value', models.DecimalField(decimal_places=2, default=0, help_text='Value in SAR (fixed) or percent (e.g. 12.5)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Markup Value')),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('thursday_close', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('saturday_close', models.TimeField(blank=True, null=True)),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('sunday_close', models.TimeField(blank=True, null=True)),
                ('first_kg_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge for the first kilogram (SAR)', max_digits=8, verbose_name='First KG Charge')),
                ('additional_kg_charge', models.DecimalField(decimal_places=2, default=0, help_text='Charge per extra kilogram (SAR)', max_digits=8, verbose_name='Additional KG Charge')),
                ('fuel_surcharge_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Additional percentage applied on total (if enabled)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Fuel Surcharge (%)')),
                ('fuel_surcharge_enabled', models.BooleanField(default=False, verbose_name='Enable Fuel Surcharge')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_cities', models.ManyToManyField(blank=True, help_text='Cities where this provider can deliver', related_name='service_providers', to='locations.city', verbose_name='Operating Cities')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['name'],
            },
        ),
    ]
