# Generated by Django 6.0.1 on 2026-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdriver',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
