# Generated by Django 6.0.1 on 2026-02-03 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstaff',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='staff_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customstaff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customstaff',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='staff_set', to='auth.permission'),
        ),
    ]
