# Generated by Django 6.0.1 on 2026-02-03 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('q_box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('package_size', models.CharField(blank=True, max_length=50)),
                ('package_weight', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Package Details',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(db_index=True, help_text='Unique tracking number', max_length=20, unique=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100)),
                ('service_provider', models.CharField(blank=True, help_text='Courier / logistics company (Aramex, DHL, local provider...)', max_length=100)),
                ('driver_name', models.CharField(blank=True, help_text='Name of driver currently assigned (if any)', max_length=100)),
                ('qr_code', models.CharField(blank=True, help_text='QR code value or URL', max_length=100)),
                ('package_status', models.CharField(choices=[('Incoming', 'Incoming'), ('Send', 'Sent')], default='Incoming', max_length=20)),
                ('shipment_status', models.CharField(choices=[('Shipment-Created', 'Shipment Created'), ('Out-for-Pickup', 'Out for Pickup'), ('Pickup-Completed', 'Pickup Completed'), ('Pickup-Failed', 'Pickup Failed'), ('Out-for-Delivery', 'Out for Delivery'), ('Issue-Logged', 'Issue Logged'), ('Delivery-Completed', 'Delivery Completed'), ('Delivery-Failed', 'Delivery Failed'), ('Return-Completed', 'Return Completed')], default='Shipment-Created', max_length=30)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last time any field was changed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('qbox', models.ForeignKey(blank=True, help_text='The Qbox this package is currently associated with / delivered to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='q_box.qbox')),
                ('details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package', to='packages.packagedetails')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='packages_pa_trackin_6d72b7_idx'), models.Index(fields=['qbox'], name='packages_pa_qbox_id_b8943c_idx'), models.Index(fields=['shipment_status'], name='packages_pa_shipmen_d54c4e_idx')],
            },
        ),
    ]
