# Generated by Django 6.0.1 on 2026-02-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('q_box', '0004_alter_qboxaccessqrcode_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_status',
        ),
        migrations.AddField(
            model_name='package',
            name='city',
            field=models.CharField(blank=True, help_text='City name (required for Incoming packages)', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='outgoing_status',
            field=models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Return', 'Return')], help_text='Status for Outgoing packages: Sent or Return', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Delivered', 'Delivered')], default='Incoming', help_text='Type of package: Incoming, Outgoing, or Delivered', max_length=20),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type'], name='packages_pa_package_759aea_idx'),
        ),
    ]
