# Generated by Django 6.0.1 on 2026-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_package_status_package_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the item in the package', max_digits=10, null=True),
        ),
    ]
