# Generated by Django 6.0.1 on 2026-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Recipient email address', max_length=254),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Recipient name for outgoing packages', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Recipient phone number', max_length=20),
        ),
    ]
