# Generated by Django 6.0.1 on 2026-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_recipient_email_package_recipient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Package description'),
        ),
    ]
