# Generated by Django 6.0.1 on 2026-02-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_charges',
            field=models.JSONField(blank=True, default=list, help_text='Payment charges as JSON array'),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_currency',
            field=models.CharField(blank=True, default='SAR', help_text='Payment currency', max_length=10),
        ),
        migrations.AddField(
            model_name='package',
            name='payment_method',
            field=models.CharField(blank=True, default='Apple Pay', help_text='Payment method for outgoing packages', max_length=50),
        ),
    ]
