# Generated by Django 6.0.1 on 2026-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_package_payment_charges_package_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.URLField(blank=True, default='', help_text='Package image URL - http://..., https://..., or base64 data URI'),
        ),
    ]
