# Generated by Django 6.0.1 on 2026-02-03 11:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_owner', '0005_remove_customhomeowner_qbox_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qbox_id', models.CharField(db_index=True, help_text='Unique device identifier (often printed on device)', max_length=20, unique=True)),
                ('homeowner_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('short_address_snapshot', models.CharField(blank=True, max_length=150)),
                ('city_snapshot', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Error', 'Error')], default='Offline', max_length=20)),
                ('led_indicator', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red')], default='Green', max_length=10)),
                ('camera_status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], default='Working', max_length=20)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qbox_image', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(blank=True, help_text='The current registered owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qboxes', to='home_owner.customhomeowner')),
            ],
            options={
                'verbose_name': 'Qbox Device',
                'verbose_name_plural': 'Qbox Devices',
                'ordering': ['-activation_date'],
                'indexes': [models.Index(fields=['qbox_id'], name='q_box_qbox_qbox_id_fa3fdb_idx'), models.Index(fields=['homeowner'], name='q_box_qbox_homeown_44f45b_idx')],
            },
        ),
    ]
