# Generated by Django 6.0.1 on 2026-02-06 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0007_alter_customhomeowner_installation_qbox_image_url'),
        ('q_box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QboxAccessQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Name for this QR code (e.g., 'Morning shift entrance')", max_length=100)),
                ('location', models.CharField(help_text="Location description (e.g., 'Box Main Entrance')", max_length=200)),
                ('address', models.CharField(help_text="Full address (e.g., 'National Address 47B')", max_length=500)),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users who can use this QR code')),
                ('current_users', models.PositiveIntegerField(default=0, help_text='Current number of users who have used this QR code')),
                ('duration_type', models.CharField(choices=[('days', 'Days'), ('minutes', 'Minutes')], default='days', help_text='Whether valid_duration is in days or minutes', max_length=20)),
                ('valid_duration', models.PositiveIntegerField(default=1, help_text='Duration value (days or minutes based on duration_type)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this QR code expires', null=True)),
                ('access_token', models.CharField(help_text='Unique access token encoded in the QR code', max_length=500, unique=True)),
                ('qr_code_url', models.URLField(blank=True, default='', help_text='URL to the generated QR code image')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(blank=True, help_text='The homeowner who created this QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qrcodes', to='home_owner.customhomeowner')),
                ('qbox', models.ForeignKey(help_text='The Qbox this QR code grants access to', on_delete=django.db.models.deletion.CASCADE, related_name='access_qrcodes', to='q_box.qbox')),
            ],
            options={
                'verbose_name': 'Qbox Access QR Code',
                'verbose_name_plural': 'Qbox Access QR Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QboxAccessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(help_text='User identifier (email, phone, or custom ID)', max_length=200)),
                ('user_name', models.CharField(blank=True, default='', help_text="User's name if provided", max_length=200)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('access_type', models.CharField(default='qr_code', help_text='Type of access (qr_code, manual, etc.)', max_length=50)),
                ('qr_code', models.ForeignKey(help_text='The QR code used for access', on_delete=django.db.models.deletion.CASCADE, related_name='access_users', to='q_box.qboxaccessqrcode')),
            ],
            options={
                'verbose_name': 'Qbox Access User',
                'verbose_name_plural': 'Qbox Access Users',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qboxaccessqrcode',
            index=models.Index(fields=['qbox'], name='q_box_qboxa_qbox_id_8b4785_idx'),
        ),
        migrations.AddIndex(
            model_name='qboxaccessqrcode',
            index=models.Index(fields=['access_token'], name='q_box_qboxa_access__513576_idx'),
        ),
        migrations.AddIndex(
            model_name='qboxaccessqrcode',
            index=models.Index(fields=['expires_at'], name='q_box_qboxa_expires_f633ea_idx'),
        ),
    ]
