# Generated by Django 6.0.1 on 2026-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_box', '0002_qboxaccessqrcode_qboxaccessuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qboxaccessqrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qrcodes/'),
        ),
    ]
