# Generated by Django 6.0.1 on 2026-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_box', '0003_qboxaccessqrcode_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qboxaccessqrcode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this QR code is currently active (manually toggled)'),
        ),
    ]
