# Generated by Django 6.0.1 on 2026-02-13 07:27

import django.db.models.deletion
import promotion.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProviderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='merchant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=promotion.models.generate_unique_code, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('promo_type', models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Flat', max_length=20)),
                ('user_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='promotion.merchantprovidername')),
            ],
        ),
    ]
