# Generated by Django 6.0.1 on 2026-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='merchant_provider_img',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_promotion_images/'),
        ),
    ]
