# Generated by Django 6.0.1 on 2026-02-13 10:28

import promotion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_merchant_provider_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='merchant_provider_img',
            field=models.ImageField(blank=True, null=True, upload_to=promotion.models.merchant_img_upload_to),
        ),
    ]
