# Generated by Django 6.0.1 on 2026-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arabic City Name')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='City Code')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
    ]
