# Generated by Django 6.0.1 on 2026-02-14 07:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0007_package_package_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('issue_related_to', models.CharField(blank=True, max_length=100, verbose_name='Issue Related To')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Package Timeline',
                'verbose_name_plural': 'Package Timelines',
                'ordering': ['-date_and_time'],
            },
        ),
    ]
