# Generated by Django 6.0.1 on 2026-02-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0002_remove_package_package_status_package_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTimeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='packages.package', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Package Timeline',
                'verbose_name_plural': 'Package Timelines',
                'ordering': ['-date_and_time'],
            },
        ),
    ]
