# Generated by Django 6.0.1 on 2026-02-12 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetimeline',
            name='issue_related_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Issue Related To'),
        ),
        migrations.AlterField(
            model_name='packagetimeline',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='packagetimeline',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='packagetimeline',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packagetimeline',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
    ]
