# Generated by Django 6.0.1 on 2026-02-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_timeline', '0002_packagetimeline_issue_related_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetimeline',
            name='city',
        ),
        migrations.RemoveField(
            model_name='packagetimeline',
            name='status',
        ),
    ]
