# Generated by Django 6.0.1 on 2026-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_timeline', '0003_remove_packagetimeline_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetimeline',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
    ]
