from django.urls import path
from .views import (
    QboxListAPIView,
    QboxDetailAPIView,
    QboxCreateAPIView,
    QboxUpdateAPIView,
    QboxStatusUpdateAPIView,
    QboxDeleteAPIView,
    VerifyQboxIdAPIView,
    QboxAccessQRCodeListAPIView,
    QboxAccessQRCodeCreateAPIView,
    QboxAccessQRCodeDetailAPIView,
    QboxAccessQRCodeAccessAPIView,
    QboxAccessQRCodeHistoryAPIView,
    QboxAccessQRCodeStatusUpdateAPIView,
    QboxAccessUsersListAPIView,
)
urlpatterns = [
    path('/', QboxListAPIView.as_view(), name='qbox-list'),
    path('/create', QboxCreateAPIView.as_view(), name='qbox-create'),
    path('/<uuid:id>', QboxDetailAPIView.as_view(), name='qbox-detail'),
    path('/<uuid:id>/update', QboxUpdateAPIView.as_view(), name='qbox-update'),
    path('/<uuid:id>/change-status', QboxStatusUpdateAPIView.as_view(), name='qbox-status'),
    path('/<uuid:id>/delete', QboxDeleteAPIView.as_view(), name='qbox-delete'),
    path('/verify-id', VerifyQboxIdAPIView.as_view(), name='verify-qbox-id'),
    path('/qr-codes/', QboxAccessQRCodeListAPIView.as_view(), name='qrcode-list'),
    path('/qr-codes/create', QboxAccessQRCodeCreateAPIView.as_view(), name='qrcode-create'),
    path('/qr-codes/<uuid:id>', QboxAccessQRCodeDetailAPIView.as_view(), name='qrcode-detail'),
    path('/qr-codes/<uuid:id>/users', QboxAccessUsersListAPIView.as_view(), name='qrcode-users'),
    path('/qr-codes/<uuid:id>/change-status', QboxAccessQRCodeStatusUpdateAPIView.as_view(), name='qrcode-status'),
    path('/qr-codes/access', QboxAccessQRCodeAccessAPIView.as_view(), name='qrcode-access'),
    path('/qr-codes/history', QboxAccessQRCodeHistoryAPIView.as_view(), name='qrcode-history'),
]
