# Generated by Django 6.0.1 on 2026-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0002_alter_customhomeowner_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhomeowner',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
