# Generated by Django 6.0.1 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0003_customhomeowner_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhomeowner',
            name='password_reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='password_reset_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
