# Generated by Django 6.0.1 on 2026-02-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0004_customhomeowner_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customhomeowner',
            name='qbox_id',
        ),
        migrations.RemoveField(
            model_name='customhomeowner',
            name='qbox_image',
        ),
        migrations.AlterField(
            model_name='customhomeowner',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='customhomeowner',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customhomeowner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customhomeowner',
            name='preferred_installment_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customhomeowner',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='building_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='district',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='secondary_building_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='short_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customhomeowneraddress',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
