# Generated by Django 6.0.1 on 2026-02-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0005_remove_customhomeowner_qbox_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhomeowner',
            name='installation_access_instruction',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='installation_location_preference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customhomeowner',
            name='installation_qbox_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
