# Generated by Django 6.0.1 on 2026-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_owner', '0006_customhomeowner_installation_access_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customhomeowner',
            name='installation_qbox_image_url',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
